version: '3.7'

services:

  database:
    image: mysql:5.7
    container_name: database
    environment:
      MYSQL_ROOT_PASSWORD: 123456
      MYSQL_DATABASE: bookstore_db
      MYSQL_USER: clarusway
      MYSQL_PASSWORD: Clarusway_1
    networks:
      - clarusnet

  myapp:
    image: bookstoreapi:latest # important to use the exact name
    container_name: bookstoreapi
    restart: always
    depends_on:
      - database
    ports: 
      - "80:80" ## left 80: ec2  source . right 80 is container, destination
    networks:
      - clarusnet
networks:
  clarusnet:  ## default is bridge, thus just leave it empty



  